--------------------------------------------------------------------------------(Solver execution current time: 3.0994415283203125e-06)
[INFO] Input Seed : 0
--------------------------------------------------------------------------------(Solver execution current time: 1.2874603271484375e-05)
[INFO] Input time limit : 15
--------------------------------------------------------------------------------(Solver execution current time: 1.7642974853515625e-05)
[INFO] Command line arguments read with no errors.
--------------------------------------------------------------------------------(Solver execution current time: 0.004198312759399414)
[INFO] Algorithm execution time : 0.004911899566650391
--------------------------------------------------------------------------------(Solver execution current time: 0.004591941833496094)
[ERROR]
An error has ocurred
Traceback (most recent call last):
  File "solver.py", line 188, in execute
    func_timeout(time_limit, run)
  File "/home/thuza/.local/lib/python3.8/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/home/thuza/.local/lib/python3.8/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "solver.py", line 95, in run
    read_input_file()
  File "solver.py", line 78, in read_input_file
    reader.read_input_file()
  File "/home/thuza/Desktop/vrp-solver/src/instance_readers/Reader.py", line 86, in read_input_file
    self.read_specific_input(file_name)
  File "/home/thuza/Desktop/vrp-solver/src/instance_readers/ReaderJsonDPDPTW.py", line 36, in read_specific_input
    fixed_points = input_dict["fixed"]
KeyError: 'fixed'

--------------------------------------------------------------------------------