--------------------------------------------------------------------------------(Solver execution current time: 6.198883056640625e-06)
[INFO] Input Seed : 6463343
--------------------------------------------------------------------------------
(Solver execution current time: 1.3113021850585938e-05)
[INFO] Input time limit : 1
--------------------------------------------------------------------------------
(Solver execution current time: 1.7642974853515625e-05)
[INFO] Command line arguments read with no errors.
--------------------------------------------------------------------------------
(Solver execution current time: 0.0008234977722167969)
[INFO] Algorithm execution time : 0.002057790756225586
--------------------------------------------------------------------------------
(Solver execution current time: 0.001340627670288086)
[ERROR]
An error has ocurred
Traceback (most recent call last):
  File "/home/loop/Desktop/vrp-solver/solver.py", line 188, in execute
    func_timeout(time_limit, run)
  File "/home/loop/.local/lib/python3.6/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/home/loop/.local/lib/python3.6/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "/home/loop/Desktop/vrp-solver/solver.py", line 95, in run
    read_input_file()
  File "/home/loop/Desktop/vrp-solver/solver.py", line 78, in read_input_file
    reader.read_input_file()
  File "/home/loop/Desktop/vrp-solver/src/instance_readers/Reader.py", line 85, in read_input_file
    self.read_specific_input(file_name)
  File "/home/loop/Desktop/vrp-solver/src/instance_readers/ReaderJsonPDPTW.py", line 165, in read_specific_input
    with open(file_name, "r") as input_file:
FileNotFoundError: [Errno 2] No such file or directory: './static_version_parametrization/instances/li_lim_LC1_10_7-100v.json'

--------------------------------------------------------------------------------
