--------------------------------------------------------------------------------(Solver execution current time: 0.00017595291137695312)
[INFO] Input Seed : 0
--------------------------------------------------------------------------------(Solver execution current time: 0.00020742416381835938)
[INFO] Input time limit : 5
--------------------------------------------------------------------------------(Solver execution current time: 0.0002319812774658203)
[INFO] Command line arguments read with no errors.
--------------------------------------------------------------------------------(Solver execution current time: 0.01778244972229004)
[INFO] Algorithm execution time : 0.018505334854125977
--------------------------------------------------------------------------------(Solver execution current time: 0.018242359161376953)
[ERROR]
An error has ocurred
Traceback (most recent call last):
  File "../solver/solver.py", line 189, in execute
    func_timeout(time_limit, run)
  File "/home/thuza/.local/lib/python3.8/site-packages/func_timeout/dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "/home/thuza/.local/lib/python3.8/site-packages/func_timeout/py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "../solver/solver.py", line 95, in run
    read_input_file()
  File "../solver/solver.py", line 78, in read_input_file
    reader.read_input_file()
  File "/home/thuza/Desktop/vrp-solver/solver/src/instance_readers/Reader.py", line 86, in read_input_file
    self.read_specific_input(file_name)
  File "/home/thuza/Desktop/vrp-solver/solver/src/instance_readers/ReaderJsonDPDPTWLimitedHybridFleet.py", line 31, in read_specific_input
    fixed_requests = input_dict["fixed"]
KeyError: 'fixed'

--------------------------------------------------------------------------------